#!/usr/bin/env bash
# Create a new Alembic migration the only safe way: autogenerated against the
# live dev DB, which is always stamped at the true current head. Hand-writing
# a migration file (or generating it against an out-of-date checkout) is what
# causes divergent-head errors — a migration can only branch off a revision
# that's stale in the AUTHOR's tree but was never actually "head" once other
# branches merged.
#
# Usage: backend/scripts/new_migration.sh "add foo column to bar"
set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 \"<migration message>\"" >&2
  exit 1
fi

cd "$(dirname "$0")/../.."

# Make sure the dev DB is actually at head before branching off it — otherwise
# we'd generate a migration on top of a stale revision.
docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm --no-deps \
  --entrypoint "" backend /app/.venv/bin/alembic upgrade head

docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm --no-deps \
  --entrypoint "" backend /app/.venv/bin/alembic revision --autogenerate -m "$1"

echo
echo "Migration created. Review the generated file in backend/alembic/versions/ before committing."
