#!/bin/bash
# ── MeetBook Local APK Builder ────────────────────────────────────────────────
# Detects your LAN IP, writes .env, builds a release APK.
# Usage: bash build-local.sh
# Output: meetbook-<version>-b<buildCode>-local.apk
# ==============================================================================

set -euo pipefail

cd "$(dirname "$0")"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Versioning ────────────────────────────────────────────────────────────────
# app.json (expo.version) is the single source of truth for the human-facing
# version. versionCode is a separate monotonically-increasing build counter
# (Android requires it to strictly increase between releases), persisted in
# .version-code and bumped once per invocation of this script.
APP_VERSION=$(python3 -c "import json; print(json.load(open('app.json'))['expo']['version'])" 2>/dev/null || echo "1.0.0")
VERSION_CODE_FILE=".version-code"
VERSION_CODE=$(($(cat "$VERSION_CODE_FILE" 2>/dev/null || echo 0) + 1))
echo "$VERSION_CODE" > "$VERSION_CODE_FILE"

# ── Display version ───────────────────────────────────────────────────────────
# Show as semver-like: app_version.build_code  (e.g., 1.1.0.1)
echo ""
echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  MeetBook v${APP_VERSION} (build ${VERSION_CODE}) — Local APK${NC}"
echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
echo ""

# ── Detect LAN IP ─────────────────────────────────────────────────────────────
detect_ip() {
  LAN_IP=$(ip -4 addr show scope global 2>/dev/null \
    | grep -oP 'inet \K[\d.]+' \
    | head -1)

  if [ -z "$LAN_IP" ]; then
    LAN_IP=$(ifconfig 2>/dev/null \
      | grep 'inet ' \
      | grep -v '127.0.0.1' \
      | awk '{print $2}' \
      | head -1)
  fi

  if [ -z "$LAN_IP" ]; then
    echo -e "${RED}❌ Could not detect LAN IP. Is your network up?${NC}"
    exit 1
  fi
}

detect_ip

API_URL="http://$LAN_IP:8000/api/v1"
OUTPUT_APK="meetbook-v${APP_VERSION}-b${VERSION_CODE}-local.apk"

echo -e "  ${BOLD}LAN IP:${NC}      $LAN_IP"
echo -e "  ${BOLD}API URL:${NC}     $API_URL"
echo -e "  ${BOLD}Version:${NC}     ${APP_VERSION} (build ${VERSION_CODE})"
echo -e "  ${BOLD}Output:${NC}      $OUTPUT_APK"
echo ""

# ── 1. Write .env ─────────────────────────────────────────────────────────────
echo -e "${YELLOW}[1/6]${NC} Writing mobile/.env → ${CYAN}$API_URL${NC}"
cat > .env <<ENV
# Auto-generated by build-local.sh — re-run if your IP changes.
EXPO_PUBLIC_API_URL=$API_URL
EXPO_PUBLIC_MAPTILER_KEY=eKJft93A5dolP425TPfm
ENV
echo "       Done."

# ── 1b. Verify API endpoint is reachable ──────────────────────────────────────
echo -e "${YELLOW}[1b]${NC} Verifying API health at ${CYAN}$API_URL/health${NC}"
HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" --max-time 3 "$API_URL/health" 2>/dev/null || echo "000")
if [ "$HEALTH_CHECK" = "200" ]; then
  echo -e "       ${GREEN}✅ API reachable (HTTP 200)${NC}"
else
  echo -e "       ${RED}⚠ API not reachable at $API_URL (HTTP $HEALTH_CHECK)${NC}"
  echo -e "       ${YELLOW}  The APK will still build but crash reports won't be sent.${NC}"
  echo -e "       ${YELLOW}  Start the backend or use a different network.${NC}"
fi
echo ""

# ── 2. Prebuild (only if android/app doesn't exist) ──────────────────────────
echo -e "${YELLOW}[2/6]${NC} Checking native project..."
if [ ! -d "android/app" ]; then
  echo "       android/ not found — running prebuild..."
  EXPO_PUBLIC_API_URL="$API_URL" npx expo prebuild --platform android --no-install 2>&1 | tail -3
else
  echo "       android/ exists — skipping prebuild (env vars injected at bundle time)"
fi
echo ""

# ── 3. Fix Android build (signing configs, ABI splits, etc) ──────────────────
echo -e "${YELLOW}[3/6]${NC} Running fix-android-build.py (v${APP_VERSION}, build ${VERSION_CODE})..."
python3 fix-android-build.py "$APP_VERSION" "$VERSION_CODE"
echo ""

# ── 4. Generate keystore if missing ──────────────────────────────────────────
echo -e "${YELLOW}[4/6]${NC} Checking release keystore..."
KEYSTORE="android/app/release.keystore"
if [ ! -f "$KEYSTORE" ]; then
  echo "       🔑 Generating release keystore..."
  keytool -genkeypair -v -storetype PKCS12 \
    -keystore "$KEYSTORE" \
    -alias meetbook-release \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass meetbook -keypass meetbook \
    -dname "CN=MeetBook, OU=Mobile, O=MeetBook, L=Istanbul, ST=Istanbul, C=TR" 2>&1 | tail -1
else
  echo "       ✅ Keystore exists."
fi
echo ""

# ── 5. Inject signing config into gradle.properties if missing ───────────────
echo -e "${YELLOW}[5/6]${NC} Checking signing config..."
GRADLE_PROPS="android/gradle.properties"
if ! grep -q "RELEASE_STORE_FILE" "$GRADLE_PROPS" 2>/dev/null; then
  echo "       ✏️  Injecting release signing config..."
  cat >> "$GRADLE_PROPS" << 'EOF'

# Release signing
RELEASE_STORE_FILE=release.keystore
RELEASE_KEY_ALIAS=meetbook-release
RELEASE_STORE_PASSWORD=meetbook
RELEASE_KEY_PASSWORD=meetbook
EOF
else
  echo "       ✅ Signing config present."
fi
echo ""

# ── 6. Build APK ──────────────────────────────────────────────────────────────
echo -e "${YELLOW}[6/6]${NC} Building release APK (arm64-v8a only)..."
echo ""

BUILD_START=$(date +%s)

cd android
EXPO_PUBLIC_API_URL="$API_URL" \
EXPO_PUBLIC_MAPTILER_KEY="eKJft93A5dolP425TPfm" \
./gradlew assembleRelease \
  -PreactNativeArchitectures=arm64-v8a \
  -Pandroid.enableMinifyInReleaseBuilds=true \
  -Pandroid.enableShrinkResourcesInReleaseBuilds=true \
  -Pandroid.enablePngCrunchInReleaseBuilds=true \
  2>&1

BUILD_END=$(date +%s)
BUILD_DURATION=$((BUILD_END - BUILD_START))
cd ..

echo ""

# ── Find and copy APK ─────────────────────────────────────────────────────────
APK_DIR="android/app/build/outputs/apk/release"
APK_FILE=$(find "$APK_DIR" -name "*.apk" 2>/dev/null | head -1)

if [ -f "$APK_FILE" ]; then
  SIZE=$(du -sh "$APK_FILE" | cut -f1)
  cp "$APK_FILE" "$OUTPUT_APK"

  echo -e "${GREEN}══════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  ✅ BUILD SUCCESSFUL${NC}"
  echo -e "${GREEN}══════════════════════════════════════════════${NC}"
  echo ""
  echo -e "  ${BOLD}Duration:${NC}    ${BUILD_DURATION}s"
  echo -e "  ${BOLD}Size:${NC}        $SIZE"
  echo -e "  ${BOLD}API URL:${NC}     $API_URL"
  echo -e "  ${BOLD}APK:${NC}         ${CYAN}$OUTPUT_APK${NC}"
  echo ""
  echo -e "  ${BOLD}Install:${NC}"
  echo -e "  ${YELLOW}adb install -r $OUTPUT_APK${NC}"
  echo -e "       (first time? adb uninstall com.canmanici.meetbook then retry)"
  echo ""
  echo -e "  ${BOLD}Share:${NC}       python3 -m http.server 8080  →  http://$LAN_IP:8080/$OUTPUT_APK"
  echo ""
else
  echo -e "${RED}❌ BUILD FAILED — no APK found in $APK_DIR${NC}"
  echo "   Scroll up and check the Gradle output for errors."
  exit 1
fi
