#!/bin/bash
# ── MeetBook Local APK Builder ────────────────────────────────────────────────
# Detects your LAN IP, writes .env, builds a release APK, and (if a device is
# reachable over wireless adb) installs it and streams logcat.
# Usage: bash build-local.sh [--publish] [--notes "…"] [--mandatory]
# Output: builds/meetbook-<version>.apk
# ==============================================================================

set -euo pipefail

cd "$(dirname "$0")"
source scripts/env-defaults.sh

# ── Options ─────────────────────────────────────────────────────────────────
#   --publish          upload the APK as an in-app update after building
#   --notes "…"        release notes shown in the update dialog
#   --mandatory        users on older versions must update
PUBLISH=0; NOTES=""; MANDATORY_FLAG=""
while [ $# -gt 0 ]; do
  case "$1" in
    --publish) PUBLISH=1; shift ;;
    --notes) NOTES="$2"; shift 2 ;;
    --mandatory) MANDATORY_FLAG="--mandatory"; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

PACKAGE_NAME="com.canmanici.meetbook"
BUILD_DIR="builds"
mkdir -p "$BUILD_DIR"

# ── Versioning ────────────────────────────────────────────────────────────────
# app.json (expo.version) is major.minor.patch; the patch number IS the build
# counter (persisted in .version-code) and is bumped once per invocation, so
# every local build gets a strictly-increasing, human-readable version like
# 1.1.18 → 1.1.19 instead of a separate "v1.1.0-b19" build suffix.
MAJOR_MINOR=$(python3 -c "import json; v=json.load(open('app.json'))['expo']['version']; print('.'.join(v.split('.')[:2]))" 2>/dev/null || echo "1.1")
VERSION_CODE_FILE=".version-code"
VERSION_CODE=$(($(cat "$VERSION_CODE_FILE" 2>/dev/null || echo 0) + 1))
echo "$VERSION_CODE" > "$VERSION_CODE_FILE"
APP_VERSION="${MAJOR_MINOR}.${VERSION_CODE}"

# Write the bumped version back into app.json (single "version" line under
# expo — a targeted regex so the rest of the file's formatting is untouched).
python3 - "$APP_VERSION" <<'PY'
import json, sys
path = "app.json"
with open(path) as f:
    data = json.load(f)
data["expo"]["version"] = sys.argv[1]
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY

# ── Display version ───────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  MeetBook v${APP_VERSION} — Local APK${NC}"
echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
echo ""

# ── Detect LAN IP ─────────────────────────────────────────────────────────────
detect_ip() {
  LAN_IP=$(ip -4 addr show scope global 2>/dev/null \
    | grep -oP 'inet \K[\d.]+' \
    | head -1)

  if [ -z "$LAN_IP" ]; then
    LAN_IP=$(ifconfig 2>/dev/null \
      | grep 'inet ' \
      | grep -v '127.0.0.1' \
      | awk '{print $2}' \
      | head -1)
  fi

  if [ -z "$LAN_IP" ]; then
    echo -e "${RED}❌ Could not detect LAN IP. Is your network up?${NC}"
    exit 1
  fi
}

detect_ip

API_URL="http://$LAN_IP:8000/api/v1"
OUTPUT_APK="$BUILD_DIR/meetbook-${APP_VERSION}.apk"

echo -e "  ${BOLD}LAN IP:${NC}      $LAN_IP"
echo -e "  ${BOLD}API URL:${NC}     $API_URL"
echo -e "  ${BOLD}Version:${NC}     ${APP_VERSION} (versionCode ${VERSION_CODE})"
echo -e "  ${BOLD}Output:${NC}      $OUTPUT_APK"
echo ""

# ── 1. Write .env ─────────────────────────────────────────────────────────────
echo -e "${YELLOW}[1/6]${NC} Writing mobile/.env → ${CYAN}$API_URL${NC}"
cat > .env <<ENV
# Auto-generated by build-local.sh — re-run if your IP changes.
EXPO_PUBLIC_API_URL=$API_URL
EXPO_PUBLIC_MAPTILER_KEY=$MAPTILER_KEY
EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=$GOOGLE_WEB_CLIENT_ID
ENV
echo "       Done."

# ── 1b. Verify API endpoint is reachable ──────────────────────────────────────
echo -e "${YELLOW}[1b]${NC} Verifying API health at ${CYAN}$API_URL/health${NC}"
HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" --max-time 3 "$API_URL/health" 2>/dev/null || echo "000")
if [ "$HEALTH_CHECK" = "200" ]; then
  echo -e "       ${GREEN}✅ API reachable (HTTP 200)${NC}"
else
  echo -e "       ${RED}⚠ API not reachable at $API_URL (HTTP $HEALTH_CHECK)${NC}"
  echo -e "       ${YELLOW}  The APK will still build but crash reports won't be sent.${NC}"
  echo -e "       ${YELLOW}  Start the backend or use a different network.${NC}"
fi
echo ""

# ── 2. Prebuild (only if android/app doesn't exist) ──────────────────────────
echo -e "${YELLOW}[2/6]${NC} Checking native project..."
if [ ! -d "android/app" ]; then
  echo "       android/ not found — running prebuild..."
  EXPO_PUBLIC_API_URL="$API_URL" npx expo prebuild --platform android --no-install 2>&1 | tail -3
else
  echo "       android/ exists — skipping prebuild (env vars injected at bundle time)"
fi
echo ""

# ── 3. Fix Android build (signing configs, ABI splits, etc) ──────────────────
echo -e "${YELLOW}[3/6]${NC} Running fix-android-build.py (v${APP_VERSION}, versionCode ${VERSION_CODE})..."
python3 fix-android-build.py "$APP_VERSION" "$VERSION_CODE"
echo ""

# ── 4. Generate keystore if missing ──────────────────────────────────────────
echo -e "${YELLOW}[4/6]${NC} Checking release keystore..."
KEYSTORE="android/app/release.keystore"
if [ ! -f "$KEYSTORE" ]; then
  echo "       🔑 Generating release keystore..."
  keytool -genkeypair -v -storetype PKCS12 \
    -keystore "$KEYSTORE" \
    -alias meetbook-release \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass meetbook -keypass meetbook \
    -dname "CN=MeetBook, OU=Mobile, O=MeetBook, L=Istanbul, ST=Istanbul, C=TR" 2>&1 | tail -1
else
  echo "       ✅ Keystore exists."
fi
echo ""

# ── 5. Inject signing config into gradle.properties if missing ───────────────
echo -e "${YELLOW}[5/6]${NC} Checking signing config..."
GRADLE_PROPS="android/gradle.properties"
if ! grep -q "RELEASE_STORE_FILE" "$GRADLE_PROPS" 2>/dev/null; then
  echo "       ✏️  Injecting release signing config..."
  cat >> "$GRADLE_PROPS" << 'EOF'

# Release signing
RELEASE_STORE_FILE=release.keystore
RELEASE_KEY_ALIAS=meetbook-release
RELEASE_STORE_PASSWORD=meetbook
RELEASE_KEY_PASSWORD=meetbook
EOF
else
  echo "       ✅ Signing config present."
fi
echo ""

# ── 6. Build APK ──────────────────────────────────────────────────────────────
echo -e "${YELLOW}[6/6]${NC} Building release APK (arm64-v8a only)..."
echo ""

BUILD_START=$(date +%s)

clear_metro_cache
rm -f android/app/build/outputs/apk/release/*.apk

cd android
# --no-daemon: the Gradle daemon is a long-lived JVM — it captures env vars
# ONCE at startup and reuses them on every later invocation, so a stale
# EXPO_PUBLIC_API_URL from a previous run (e.g. after switching wifi networks)
# silently gets baked into the JS bundle instead of the current LAN IP. This
# was causing "sunucu bağlanamadı" on APKs built after an IP change. Building
# without the daemon costs a bit of time but guarantees a fresh env every run.
EXPO_PUBLIC_API_URL="$API_URL" \
EXPO_PUBLIC_MAPTILER_KEY="$MAPTILER_KEY" \
EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID" \
# --no-build-cache: a stale cached mergeReleaseAssets once produced an APK
# with NO JS bundle (app dead on launch). Local cache still speeds up native
# compilation via up-to-date checks; only cross-run cache restores are off.
./gradlew assembleRelease --no-build-cache \
  -PreactNativeArchitectures=arm64-v8a \
  -PmeetbookAbis=arm64-v8a \
  -Pandroid.enableMinifyInReleaseBuilds=false \
  -Pandroid.enableShrinkResourcesInReleaseBuilds=false \
  -Pandroid.enablePngCrunchInReleaseBuilds=false \
  2>&1

BUILD_END=$(date +%s)
BUILD_DURATION=$((BUILD_END - BUILD_START))
cd ..

echo ""

# ── Find and copy APK ─────────────────────────────────────────────────────────
APK_DIR="android/app/build/outputs/apk/release"
APK_FILE="$APK_DIR/app-arm64-v8a-release.apk"

if [ ! -f "$APK_FILE" ]; then
  echo -e "${RED}❌ BUILD FAILED — no APK found in $APK_DIR${NC}"
  echo "   Scroll up and check the Gradle output for errors."
  exit 1
fi

SIZE=$(du -sh "$APK_FILE" | cut -f1)
cp "$APK_FILE" "$OUTPUT_APK"

echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ BUILD SUCCESSFUL${NC}"
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Duration:${NC}    ${BUILD_DURATION}s"
echo -e "  ${BOLD}Size:${NC}        $SIZE"
echo -e "  ${BOLD}API URL:${NC}     $API_URL"
echo -e "  ${BOLD}Google ID:${NC}   ${GOOGLE_WEB_CLIENT_ID:-(none — Google button hidden)}"
echo -e "  ${BOLD}Signed SHA-1:${NC} $(apk_sha1 "$OUTPUT_APK")  (must be on Google's Android OAuth client)"
echo -e "  ${BOLD}APK:${NC}         ${CYAN}$OUTPUT_APK${NC}"
echo ""

# Sanity: the values must really be inside the JS bundle (stale Metro cache
# has silently shipped old URLs before).
BUNDLE=$(unzip -p "$OUTPUT_APK" assets/index.android.bundle 2>/dev/null | tr -d '\000' || true)
if ! grep -qaF "$API_URL" <<<"$BUNDLE"; then
  echo -e "  ${RED}⚠ API URL not found in the bundle — do not ship this APK.${NC}"
fi
if [ -n "$GOOGLE_WEB_CLIENT_ID" ] && ! grep -qaF "$GOOGLE_WEB_CLIENT_ID" <<<"$BUNDLE"; then
  echo -e "  ${RED}⚠ Google client ID not found in the bundle — Google login will be hidden.${NC}"
fi

if [ "$PUBLISH" = "1" ]; then
  echo -e "${YELLOW}[publish]${NC} Uploading as in-app update to ${CYAN}$API_URL${NC}"
  bash scripts/publish-apk.sh "$OUTPUT_APK" --api "$API_URL" --notes "$NOTES" $MANDATORY_FLAG || true
  echo ""
fi

# ── 7. Wireless install + live debug (no USB required) ───────────────────────
# Looks for a device already reachable over adb (wifi pairing done once via
# `adb pair`/`adb connect`, no cable needed afterwards). If found, installs
# the APK and streams filtered logcat, like the live output of `npm run android`.
WIRELESS_DEVICE=$(adb devices 2>/dev/null | awk '$2=="device" && $1 ~ /:/ {print $1; exit}')
# Real phones first: this arm64 APK won't install on an x86_64 emulator.
ANY_DEVICE=$(adb devices 2>/dev/null | awk '$2=="device" && $1 !~ /^emulator-/ {print $1; exit}')
TARGET_DEVICE="${WIRELESS_DEVICE:-$ANY_DEVICE}"

if [ -n "$TARGET_DEVICE" ]; then
  echo -e "  ${BOLD}Device:${NC}      $TARGET_DEVICE"
  echo -e "${YELLOW}[7/7]${NC} Installing on $TARGET_DEVICE and streaming logcat (Ctrl+C to stop)..."
  adb -s "$TARGET_DEVICE" install -r "$OUTPUT_APK" || {
    echo -e "       ${RED}Install failed — try: adb -s $TARGET_DEVICE uninstall $PACKAGE_NAME${NC}"
  }
  PID=$(adb -s "$TARGET_DEVICE" shell pidof "$PACKAGE_NAME" 2>/dev/null | tr -d '\r')
  adb -s "$TARGET_DEVICE" logcat -c
  echo ""
  adb -s "$TARGET_DEVICE" logcat --pid="${PID:-}" 2>/dev/null || adb -s "$TARGET_DEVICE" logcat "*:S" "ReactNative:V" "ReactNativeJS:V" "AndroidRuntime:E"
else
  echo -e "  ${YELLOW}No adb device connected — skipping install/logcat.${NC}"
  echo ""
  echo -e "  ${BOLD}Wireless debugging (one-time setup, no cable after this):${NC}"
  echo -e "    1. Phone: Settings → Developer options → Wireless debugging → Pair device with code"
  echo -e "    2. adb pair <ip>:<pairing-port> <pairing-code>"
  echo -e "    3. adb connect <ip>:<connect-port>"
  echo -e "  Then just re-run this script — it'll auto-install and tail logs."
  echo ""
  echo -e "  ${BOLD}Manual install:${NC}"
  echo -e "  ${YELLOW}adb install -r $OUTPUT_APK${NC}"
  echo ""
  echo -e "  ${BOLD}Share:${NC}       python3 -m http.server 8080 --directory $BUILD_DIR  →  http://$LAN_IP:8080/$(basename "$OUTPUT_APK")"
  echo ""
fi
