#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# detect-api-url.sh — One-stop dev environment setup
#
# Detects the current LAN IP and updates ALL endpoints in one go:
#   1. mobile/.env           → EXPO_PUBLIC_API_URL
#   2. project root .env     → LAN_IP (used by docker-compose.yml)
#   3. Restarts backend to pick up new S3_EXTERNAL_ENDPOINT
#   4. Sets MinIO bucket policy for anonymous read access
#   5. Starts Expo
#
# Usage: npm run start:lan
# =============================================================================

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
MOBILE_DIR="$ROOT_DIR/mobile"
source "$MOBILE_DIR/scripts/env-defaults.sh"

# --- 1. Detect LAN IP -------------------------------------------------------
LAN_IP=$(ip -4 addr show scope global 2>/dev/null \
  | grep -oP 'inet \K[\d.]+' \
  | head -1)

if [ -z "$LAN_IP" ]; then
  LAN_IP=$(ifconfig 2>/dev/null \
    | grep 'inet ' \
    | grep -v '127.0.0.1' \
    | awk '{print $2}' \
    | head -1)
fi

if [ -z "$LAN_IP" ]; then
  echo "ERROR: Could not detect LAN IP. Falling back to localhost."
  LAN_IP="localhost"
fi

echo ""
echo "=========================================="
echo " LAN IP: $LAN_IP"
echo "=========================================="
echo ""

# --- 2. Update mobile/.env --------------------------------------------------
cat > "$MOBILE_DIR/.env" <<ENV
# Auto-generated by detect-api-url.sh — re-run if your IP changes.
EXPO_PUBLIC_API_URL=http://$LAN_IP:8000/api/v1
EXPO_PUBLIC_MAPTILER_KEY=$MAPTILER_KEY
ENV
echo "[1/4] Updated mobile/.env → EXPO_PUBLIC_API_URL=http://$LAN_IP:8000/api/v1"

# --- 3. Update root .env (used by docker-compose.yml) -----------------------
cat > "$ROOT_DIR/.env" <<ENV
# Auto-generated by detect-api-url.sh — re-run if your IP changes.
LAN_IP=$LAN_IP
ENV
echo "[2/4] Updated root .env → LAN_IP=$LAN_IP"

# --- 4. Restart backend with new S3_EXTERNAL_ENDPOINT -----------------------
cd "$ROOT_DIR"
echo "[3/4] Restarting backend (S3_EXTERNAL_ENDPOINT=http://$LAN_IP:9100) ..."
docker compose up -d backend 2>&1 | tail -2

echo -n "       Waiting for backend "
for i in $(seq 1 30); do
  if curl -sf "http://localhost:8000/api/v1/health" > /dev/null 2>&1; then
    echo " ready!"
    break
  fi
  echo -n "."
  sleep 1
done
echo ""

# --- 5. Set MinIO bucket policy for anonymous read access --------------------
echo "[4/4] Setting MinIO bucket anonymous read policy ..."
docker compose exec -T minio sh -c \
  "mc alias set local http://localhost:9000 meetbook_minio meetbook_minio_dev 2>/dev/null && mc anonymous set download local/meetbook-photos 2>&1" \
  || echo "       (will be set after first upload)"
echo ""

# --- 6. Summary --------------------------------------------------------------
echo "=========================================="
echo " All endpoints updated!"
echo "=========================================="
echo ""
echo " Backend API:     http://$LAN_IP:8000/api/v1"
echo " MinIO Console:   http://$LAN_IP:9101"
echo " MinIO S3 API:    http://$LAN_IP:9100"
echo " Expo Dev:        exp://$LAN_IP:8081"
echo ""

# --- 7. Start Expo -----------------------------------------------------------
cd "$MOBILE_DIR"
exec npm run start -- "$@"
